---
collections:
        - name: vmware.vmware_rest
        - name: community.vmware
        - name: openstack.cloud
        - name: redhat.rhel_system_roles
          # version: 1.7.3
          source: https://cloud.redhat.com/api/automation-hub/
        - name: community.general
        - name: ansible.posix
        - name: community.sap_libs
        - name: community.sap_operations
        - name: https://github.com/sap-linuxlab/community.sap_install.git,dev
          type: git
        - name: https://github.com/sap-linuxlab/community.sap_launchpad.git,dev
          type: git
