---
collections:
        - name: vmware.vmware_rest
          version: 2.1.5
        - name: community.vmware
          version: 2.6.0
        - name: redhat.rhel_system_roles
          version: 1.7.3
          source: https://cloud.redhat.com/api/automation-hub/
        - name: community.general
          version: 4.3.0
        - name: community.sap_libs
        - name: community.sap_operations
        - name: https://github.com/mmoster/community.sap_install.git,dev
          type: git
        - name: https://github.com/sap-linuxlab/community.sap_launchpad.git
          type: git
