---
####################################################
#
# Phase 2: Basic OS Setup
#
# This playbook covers the following configuration steps
#  - network
#  - timesync
#  - storage customization
#  - subscription

# Variables for parameterizing this playbook are stored
# either in hostvars/groupvars directory or in the corresponding
# inventory settings in AWX or Controller

- name: Phase 2 - basic OS Setup
  hosts: all
  become: true

  tasks:
    - name: Ensure network is configured correctly
      include_role:
        name: fedora.linux_system_roles.network

    - name: Ensure timesync is configured correctly
      include_role:
        name: fedora.linux_system_roles.timesync

    - name: Ensure system is properly subscribed
      include_role:
        name: community.sap_operations.sap_rhsm

    - name: Ensure storage is configured correctly
      include_role:
        name: fedora.linux_system_roles.storage
