- name: Create AWX Ingress 
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: "{{ awxsetup.name }}-ingress"
        namespace: "{{ awxsetup.namespace }}"
      spec:
        rules:
        - host: "{{ awxsetup.name }}.{{ awxsetup.baseurl }}"
          http:
            paths:
            - pathType: Prefix
              path: "/"
              backend:
                service: 
                  name: "{{ awxsetup.name }}-service"
                  port:
                    number: 80

