---
# Phase 3 - step A
#
# This playbook configures all systems in the
# HANA Group for consumption of SAP HANA software

- name: Phase 3-A - Prepare system for SAP HANA Installation
  hosts: "{{ group_hana | d('hanas') }}"
  become: true

  roles:
     - community.sap_install.sap_general_preconfigure
     - community.sap_install.sap_hana_preconfigure
