---
# Phase 3 - step B
#
# The role sap_hana_install unpacks the software in {{ sap_hana_install_software_directory }}
# Then it calls the installation of SAP HANA with the configured paramters

- name: Phase 3-B - Install Hana
  hosts: "{{ group_hana | d('hanas') }}"
  become: true

  tasks:
    # This step is already included in version 1.0.2. of the collection
    # name: Detect Existing HANA installation
    #  include_tasks: check_for_sap_instances.yml

    - name: Execute the SAP Hana Installation
      ansible.builtin.include_role:
        name: community.sap_install.sap_hana_install
