---
#
# The role sap_swpm unpacks thes software found in {{ sap_swpm_software_path }}
# Then it calls the installation of sapinst with the configured paramters
#

- name: Install S4
  hosts: s4hanas
  become: true

  tasks:
    - name: Output all variables
      debug:
        var: hostvars[inventory_hostname]
        verbosity: 1

    # The following tasks are a work around until the extract directory
    # can be specified in the parameters of sap_swpm
    #
    #  if you set sap_swpm_software_path in your template it will overwrite these settings
    #  it is basically identical to sap_swpm_software_extract_directory
    #
    - name: Create local directory "{{ sap_swpm_software_extract_directory }}"
      ansible.builtin.file:
        path: '{{ sap_swpm_software_extract_directory }}'
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: copy installation archives from NFS to local disk
      ansible.builtin.copy:
        src: "{{ sap_swpm_software_directory + '/' }}"
        dest: "{{ sap_swpm_software_extract_directory + '/'}}"
        remote_src: true

    - name: execute the SWPM Installation
      include_role:
        name: community.sap_install.sap_swpm
      vars:
        sap_swpm_software_path: "{{ sap_swpm_software_extract_directory }}"

