---
#  update_etc_hosts
#
#  This role udates the DNS server

- name: Ensure all hosts are in /etcHosts
  hosts: hanas,s4hanas
  become: true

  tasks:
    - name: Host IP to add
      ansible.builtin.debug:
        var: hostvars['{{ item }}'].ansible_host
      loop: "{{ play_hosts }}"

    - name: Execute role
      ansible.builtin.include_role:
        name: update_etc_hosts
      vars:
        update_etc_hosts_list:
          - node_ip: hostvars['{{ item }}'].ansible_host
            node_name: item
      loop: "{{ play_hosts }}"
