---
# Thanks to https://gryzli.info/2017/12/21/ansible-debug-print-variables/
- name: dump all vars
  hosts: all
  gather_facts: true

  tasks:
    - name: Print some debug information
      vars:
        msg: |
          Module Variables ("vars"):
          --------------------------------
          {{ vars | to_nice_json }}

          Environment Variables ("environment"):
          --------------------------------
          {{ environment | to_nice_json }}

          GROUP NAMES Variables ("group_names"):
          --------------------------------
          {{ group_names | to_nice_json }}

          GROUPS Variables ("groups"):
          --------------------------------
          {{ groups | to_nice_json }}

          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_json }}

      debug:
        msg: "{{ msg.split('\n') }}"
      tags: debug_info
